# Generated by Django 4.2 on 2023-10-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrisFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepal_length', models.CharField(max_length=300)),
                ('sepal_width', models.CharField(max_length=300)),
                ('petal_length', models.CharField(max_length=300)),
                ('petal_width', models.CharField(max_length=300)),
                ('species', models.CharField(max_length=300)),
            ],
        ),
    ]
