# Generated by Django 4.2.6 on 2023-10-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepal_length', models.CharField(max_length=200)),
                ('sepal_width', models.CharField(max_length=200)),
                ('petal_length', models.CharField(max_length=200)),
                ('petal_width', models.CharField(max_length=200)),
                ('species', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
